### ISSUE TITLE
Deployment fails due to verification issue bind_tls: Unsupported value: "true": supported values: "true", "false", "both"

### ISSUE THREAD

**Issue by kriss-s** [zufardhiyaulhaq/ngrok-operator#16]
https://github.com/zufardhiyaulhaq/ngrok-operator/blob/542f7d137129e935132800475f9d195a664d8119/charts/ngrok-operator/crds/crds.yaml#L58

This fails to verify strings `"true" | "false"` (and actual bool values fail the type check) as the CRD contain bool values for comparison for the string type and not strings.

> * spec.bind_tls: Unsupported value: "true": supported values: "true", "false", "both"

> * spec.bind_tls: Invalid value: "boolean": spec.bind_tls in body must be of type string: "boolean"
> * spec.bind_tls: Unsupported value: true: supported values: "true", "false", "both"

should be
```yaml
              bind_tls:
                enum:
                - "true"
                - "false"
                - "both"
                type: string

```
